### ISSUE TITLE
`ERR_REQUIRE_ESM` error when using `@textile/eth-storage`

### ISSUE THREAD

**Issue by askender** [textileio/storage-js#22]
**Describe the bug**
```
yarn run v1.22.10
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 4. Reason: webpack5 flag is set to false in next.config.js https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /userxxx/aproject/node_modules/@textile/eth-storage/dist/cjs/index.js
require() of ES modules is not supported.
require() of /userxxx/aproject/node_modules/@textile/eth-storage/dist/cjs/index.js from /userxxx/aproject/.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /userxxx/aproject/node_modules/@textile/eth-storage/dist/cjs/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /userxxx/aproject/node_modules/@textile/eth-storage/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at eval (webpack-internal:///@textile/eth-storage:1:18)
    at Object.@textile/eth-storage (/userxxx/aproject/.next/server/pages/index.js:149:1)
    at __webpack_require__ (/userxxx/aproject/.next/server/pages/index.js:23:31)
    at eval (webpack-internal:///./pages/index.js:18:78)
    at Module../pages/index.js (/userxxx/aproject/.next/server/pages/index.js:138:1)
    at __webpack_require__ (/userxxx/aproject/.next/server/pages/index.js:23:31)
    at /userxxx/aproject/.next/server/pages/index.js:91:18
    at Object.<anonymous> (/userxxx/aproject/.next/server/pages/index.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at requirePage (/userxxx/aproject/node_modules/next/dist/next-server/server/require.js:1:1519)
    at loadComponents (/userxxx/aproject/node_modules/next/dist/next-server/server/load-components.js:1:1442) {
  code: 'ERR_REQUIRE_ESM'
}
```

**To Reproduce**

```
follow https://eth.storage/javascript/#eth--polygon in a next.js project.
```

**Expected behavior**
no `ERR_REQUIRE_ESM` error 

**Additional context**
After I remove `"type": "module"` from  /userxxx/aproject/node_modules/@textile/eth-storage/package.json and /userxxx/aproject/node_modules/@textile/core-storage/package.json 
this problem solved, but it's not friendly to users.

**Comment by askender** [comment]
It has problem on macos, node v14.18.0.
It's ok on linux, node v14.17.2.
Close it.  Maybe it's related to node version or difference between systems.

**Comment by askender** [comment]
It has problem on   macos, node v14.18.0.  while running `next dev`
It has same problem on linux, node v14.17.2, while running `next build`
